"""empty message

Revision ID: 9a58aed06a17
Revises: adfb2b3f95ea
Create Date: 2025-05-03 09:35:12.429149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a58aed06a17'
down_revision = 'adfb2b3f95ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
