"""empty message

Revision ID: c8897f6085ad
Revises: ff2ed307620f
Create Date: 2025-05-06 09:40:16.808674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8897f6085ad'
down_revision = 'ff2ed307620f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo1', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('photo2', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('photo3', sa.String(length=150), nullable=True))
        batch_op.drop_column('post_1')
        batch_op.drop_column('post_2')
        batch_op.drop_column('post_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_3', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_2', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_1', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('photo3')
        batch_op.drop_column('photo2')
        batch_op.drop_column('photo1')

    # ### end Alembic commands ###
