"""empty message

Revision ID: 24f50ef6345b
Revises: 08cea23bb82e
Create Date: 2025-05-03 19:09:10.716869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f50ef6345b'
down_revision = '08cea23bb82e'
branch_labels = None
depends_on = None


def upgrade():
    # Set a default value for rows with NULL 'user_id'

    # Apply the NOT NULL constraint
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE events SET user_id = 1 WHERE user_id IS NULL')
