"""optional end time

Revision ID: 60be0e94da4b
Revises: 70a2b3c2f2e9
Create Date: 2025-05-05 11:29:05.931242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60be0e94da4b'
down_revision = '70a2b3c2f2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('end')

    # ### end Alembic commands ###
