"""empty message

Revision ID: adfb2b3f95ea
Revises: 52f038d9eb7c
Create Date: 2025-05-01 11:32:37.685811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfb2b3f95ea'
down_revision = '52f038d9eb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), server_default='teacher', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###
