"""empty message

Revision ID: ff2ed307620f
Revises: bca4c7d77689
Create Date: 2025-05-06 09:05:27.603915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2ed307620f'
down_revision = 'bca4c7d77689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_3', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('post_3')
        batch_op.drop_column('post_2')
        batch_op.drop_column('post_1')
        batch_op.drop_column('major')

    # ### end Alembic commands ###
